### ISSUE TITLE
Configuration driven commands

### ISSUE THREAD

**Issue by tuler** [cartesi/cli#31]
## 📚 Context

The current CLI commands like `build` and `run` currently allow some level of customization through the following mechanisms:

- machine rootfs contents from a Docker image
- RAM memory size from a Docker label
- drive extra space from a Docker label
- emulator version (or kernel) by replacing an underlying "sdk Docker image"

This process is kind of scattered and makes it hard to allow further customization required by some applications or different frameworks like lambada.

## ✔️ Solution

Implement build and execution driven by a configuration file.
The configuration will be a [TOML](https://toml.io) file containing sections for machine drives, kernel configuration, runtime configuration, etc.

The configuration file content can be discussed further in this issue.
Ideally the file can be considered optional for a project if all options have a default value.

## 📈 Subtasks

- [ ] define the file content, and the default values
- [ ] implement the `build` command using the configuration
- [ ] implement the `run` command using the configuration
- [ ] implement the `deploy` command using the configuration

## 🎯 Definition of Done

- [ ] build based on configuration
- [ ] run based on configuration
- [ ] allow novel use cases for the CLI, like lambada applications

**Comment by guidanoli** [comment]
So, right off the bat, I think these labels would turn into key-value pairs in this TOML file, right?

```dockerfile
LABEL io.cartesi.sdk_version=0.6.0
LABEL io.cartesi.rollups.ram_size=128Mi
LABEL io.cartesi.rollups.data_size=128Mb
```

:arrow_right:

```toml
sdk_version = "0.6.0"
ram_size = "128Mi"
data_size = "128Mb"
```

**Comment by tuler** [comment]
> So, right off the bat, I think these labels would turn into key-value pairs in this TOML file, right?

Like that, but with a better structure.

First, for drives I'm considering something like:

```toml
[drives.root]
filename = "rootfs.ext2"
```

Where `root` is the drive label.
Filename is the `ext2` or `sqfs` filename, in case the drive already exists (from another external process).

For the drives that are about to be "produced" by the `build` command, instead of defining a `filename` I'd define a `builder = docker` property, and an optional `dockerfile` with the path to Dockerfile, like this:

```toml
[drives.root]
builder = "docker"
dockerfile = "Dockerfile"
```

The above can actually be the default behavior, so It would work as it is now.

In addition there are the following properties, which are self-explanatory.

```toml
shared = true
mount = "/"
user = "dapp"
```

I'm not sure if the drive memory start and size should be configurable. Maybe there is a use case for that.

**Comment by tuler** [comment]
> Perhaps something like this?
> 
> ```
> ['state.raw']
> builder = pristine
> length = 10Mi
> ```

I don't like that format very much. It's not very toml'ish to have dynamic keys like that, except when "under" a certain key, like what I did with `driver.<label>`. Usually toml keys are known and parsed explicitly. The parse of your suggestion would have to follow a dependency mechanism like what happens with Makefile (which is probably where you are coming from).

**Comment by tuler** [comment]
> uses JSON to specify the machine configuration to simplify the types

That feature of the cartesi-machine may have a positive impact on this feature of the CLI, because the CLI could either accept a machine JSON from the application, instead of replicating those in a TOML format, and leave the TOML only for drive building procedure definition.

The other option would be to continue on this path of defining machine configuration in TOML, and generating a JSON for the cartesi-machine, which will most likely be required anyway when 0.20 comes out, unless you keep compatibility with the currently behavior of `cartesi-machine.lua`.

What are your thoughts on that @diegonehab
