### ISSUE TITLE
ERC-4377 support

### ISSUE THREAD

**Issue by tuler** [cartesi/cli#38]
## 📚 Context

Account Abstraction ([ERC-4377](https://www.erc4337.io)) is an important feature of EVM networks, providing several usability improvements.

Cartesi applications are already compatible with Account Abstraction. There is no change necessary to a Cartesi application to support ERC-4377. Advance requests arrive normally to a Cartesi backend.

But on the other hand the frontend of an application needs to implement support to ERC-4377.
When using a testnet there are several service providers that offer the necessary infrastructure to implement ERC-4377 (Alchemy, ZeroDev, Biconomy, Stackup, etc)

But on a local development environment, using the Cartesi CLI we need to provide that support.

## ✔️ Solution

The required infrastructure for ERC-4377 includes the following:

- several smart contracts deployed to the local `anvil` instance. This includes core contracts and popular smart wallets factories.
- a bundler server
- a paymaster server

Pimlico provides documentation about how to run a [ERC-4377 infrastructure locally](https://github.com/pimlicolabs/mock-aa-environment). It consists of deploying a [set of smart contracts](https://github.com/pimlicolabs/mock-aa-environment/blob/main/mock-alto-bundler/src/constants.ts), and running a local instance of [alto](https://github.com/pimlicolabs/alto) and a [mock paymaster](https://github.com/pimlicolabs/mock-aa-environment/blob/main/mock-verifying-paymaster/src/relay.ts).

If the developer wants to use a passkey signer he will also need a passkey server. One implementation is provided by [ZeroDev](https://github.com/zerodevapp/passkey-server).

[Alto](https://github.com/pimlicolabs/alto) is one popular implementation of a bundler. It's written in typescript, and already has a docker image part of its release process.

## 📈 Subtasks

- [x] deploy ERC-4377 support contract to the `devnet`
- [x] add the bundler to the SDK
- [x] add the paymaster to the SDK
- [x] add the bundler to the `cartesi run`
- [x] add the paymaster to the `cartesi run`

## 🎯 Definition of Done

- [x] use the CLI bundler and paymaster with Cartesi applications frontends.
