### ISSUE TITLE
Add espresso dev node to cli compose

### ISSUE THREAD

**Issue by endersonmaia** [cartesi/cli#79]
## 📚 Context

So that developer can experiment applications using espresso sequencer during local development, we need to provide a espresso dev node as a service.

## ✔️ Solution

Add the espresso dev container to our compose

https://github.com/EspressoSystems/espresso-sequencer/blob/main/doc/espresso-dev-node.md

## 📈 Subtasks

-   [ ] add espresso dev node as a container to our compose
-   [ ] publish its API through traekif ever proxy
-   [ ] allow to disable the service with `--disable-espresso`

## 🎯 Definition of Done

-   [ ] `cartesi run` should start an espresso dev node and export its API endpoint to localhost

**Comment by endersonmaia** [comment]
Whe I start a `espresso-dev-node` connected to anvil and postgres from  `cartesi run` I can see that the `sequencer` database created for espresso gets populated and I see at anvil logs that some contracts are created.

We can see in  dev-info API we have the LIghtClient address, for ex.:

```shell
curl -fssL -X GET localhost:20000/api/dev-info | jq .
{
  "builder_url": "http://localhost:8771/",
  "l1_prover_port": 8772,
  "l1_url": "http://anvil:8545/",
  "l1_light_client_address": "0x5f3f1dbd7b74c6b46e8c44f98792a1daf8d69154",
  "alt_chains": []
}
```

**Comment by endersonmaia** [comment]
It was delivered at https://github.com/cartesi/cli/commit/e79c0bb4e3f4f8e85af3703a051386878b03df4c

Needs more tests anyway

**Comment by tuler** [comment]
Need to redefine how this will work with `cartesi rollups start`.
Maybe a good one is `cartesi rollups start --sequencer espresso`.
